version: 2
jobs:
  build:
    working_directory: ~/minuet
    docker:
      - image: node:8.9.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: npm run build
      - run:
          name: Run tests
          command: npm test
      - deploy:
          name: Publish to NPM
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              if [[ $(git describe --tags) =~ ^v[0-9]+(\.[0-9]+)+(-rc[0-9]+)?(-alpha[0-9]+)?$ ]]; then
                echo "//registry.npmjs.org/:_authToken=$NPM_AUTH" >> ~/.npmrc
                npm publish
                echo "Successfully published to NPM"
              else
                echo "Skipping publish because this is not a release"
              fi
            fi
      - deploy:
          name: Publish docs to GitHub pages
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              if [[ $(git describe --tags) =~ ^v[0-9]+(\.[0-9]+)+(-rc[0-9]+)?(-alpha[0-9]+)?$ ]]; then
                if [ `git branch | grep gh-pages` ]
                then
                  git branch -D gh-pages
                fi
                git checkout -b gh-pages
                npm run docs

                # Move generated docs to root and delete everything else.
                find . -maxdepth 1 ! -name '.' ! -name '..' ! -name 'docs' ! -name '.git' ! -name '.gitignore' -exec rm -rf {} \;
                mv docs/* .
                rm -R docs/

                # Push to gh-pages.
                ORIGIN_URL=`git config --get remote.origin.url`

                git config user.name "$GITHUB_USERNAME"
                git config user.email "$GITHUB_EMAIL"
                git add -fA
                git commit --allow-empty -m "$(git log -1 --pretty=%B) [ci skip]"
                git push -f $ORIGIN_URL gh-pages

                echo "Successfully published docs to GitHub pages"
              else
                echo "Skipping publish because this is not a release"
              fi
            fi
