on:
  workflow_call:
jobs:
  default:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Restore lib dir
        uses: actions/download-artifact@v1
        with:
          name: lib
      - name: Create release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.github_token }}
          script: |
            const tag = process.env.GITHUB_REF.split('/').slice(-1)[0]
            try {
              await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: tag,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: tag,
              })
            }
            catch (error) {
              core.setFailed(error.message)
            }
      - name: Deploy to NPM
        run: .github/workflows/deploy_to_npm.sh
        env:
          NPM_AUTH: ${{ secrets.NPM_AUTH }}
