on:
  workflow_call:
jobs:
  default:
    name: Release
    runs-on: ubuntu-latest
    container: node:18.8.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore lib dir
        uses: actions/download-artifact@v1
        with:
          name: lib
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body_path: RELEASE.md
          draft: false
          prerelease: false
      - name: Deploy to NPM
        run: .github/workflows/deploy_to_npm.sh
        env:
          NPM_AUTH: ${{ secrets.NPM_AUTH }}
